export const REQUEST_SCHEMA = {
  type: 'object',
  properties: {
    call_id: {
      type: 'string',
      description: 'Correlation ID of the tool call.',
    },
    function: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Name of the function to call.',
        },
        arguments: {
          type: 'string',
          description:
            'Arguments to call the function with, as generated by the model in JSON format.',
        },
      },
      required: ['name', 'arguments'],
    },
    context: {
      type: 'object',
      properties: {
        dir: {
          type: 'string',
          description: 'Full path to the current directory.',
        },
      },
      required: ['dir'],
    },
  },
  required: ['call_id', 'function', 'context'],
}
