type ToolRequest = {
  /** Correlation ID of the tool call. */
  call_id: string

  /** The function that the model called. */
  function: ToolRequestFunction

  /** Context of the tool call request. */
  context: ToolRequestContext
}

export type ToolRequestFunction = {
  /** Name of the function to call. */
  name: string

  /** Arguments to call the function with, as generated by the model in JSON format. */
  arguments: string
}

export type ToolRequestContext = {
  /** Full path to the current directory. */
  dir: string
}

export type ToolResponse = {
  /** ID of the tool call that this message is responding to. */
  call_id: string

  /** The contents of the tool response. */
  content?: unknown
}

export default ToolRequest
