import Ajv from './Ajv'

const REQUEST_SCHEMA = {
  type: 'object',
  properties: {
    call_id: {
      type: 'string',
      description: 'Correlation ID of the tool call.',
    },
    function: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description: 'Name of the function to call.',
        },
        arguments: {
          type: 'string',
          description:
            'Arguments to call the function with, as generated by the model in JSON format.',
        },
      },
      required: ['name', 'arguments'],
    },
    context: {
      type: 'object',
      properties: {
        dir: {
          type: 'string',
          description: 'Full path to the current directory.',
        },
      },
      required: ['dir'],
    },
  },
  required: ['call_id', 'function', 'context'],
}

const ARGS_SCHEMA = {
  type: 'object',
  properties: {
    message: {
      type: 'string',
      description: 'The message content.',
    },
  },
  required: ['message'],
}

export type ToolRequestFunction = {
  /** Name of the function to call. */
  name: string

  /** Arguments to call the function with, as generated by the model in JSON format. */
  arguments: string
}

export type ToolRequestContext = {
  /** Full path to the current directory. */
  dir: string
}

export type ToolRequest = {
  /** Correlation ID of the tool call. */
  call_id: string

  /** The function that the model called. */
  function: ToolRequestFunction

  /** Context of the tool call request. */
  context: ToolRequestContext
}

export type ToolResponse = {
  /** ID of the tool call that this message is responding to. */
  call_id: string

  /** The contents of the tool response. */
  content?: unknown
}

// New type for message request.
export type MessageRequest = {
  /** Message content. */
  message: string
}

function getRequest(value: string): ToolRequest {
  const request = JSON.parse(value)

  if (!Ajv.validate(REQUEST_SCHEMA, request)) {
    throw new Error("The request didn't match the request schema.")
  }

  return request as ToolRequest
}

export function getRequestArgs(value: string): MessageRequest {
  const request = JSON.parse(value)

  if (!Ajv.validate(ARGS_SCHEMA, request)) {
    throw new Error("The arguments didn't match the arguments schema.")
  }

  return request as MessageRequest
}

export default getRequest
